apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - env:
            - name: PMA_HOST
              value: db
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              value: somewordpress
          image: phpmyadmin/phpmyadmin
          name: php
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
