apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dolibarr
  name: dolibarr
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: dolibarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: dolibarr
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          command: ["sh", "-c", "sleep 30"]
      containers:
        - image: uccef/dolibarr.dev:latest
          name: dolibarr
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: dolibarr-configmap
            - secretRef:
                name: dolibarr-secret-config
          imagePullPolicy: Always
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html/htdocs/conf/
              name: dolibarr-conf
            - mountPath: /var/www/documents
              name: dolibarr-docs
      restartPolicy: Always
      volumes:
        - name: dolibarr-conf
          persistentVolumeClaim:
            claimName: dolibarr-conf
        - name: dolibarr-docs
          persistentVolumeClaim:
            claimName: dolibarr-docs