apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dolibarr
  name: dolibarr
spec:
  type: LoadBalancer
  ports:
    - name: "8200"
      port: 8200
      targetPort: 80
  selector:
    io.kompose.service: dolibarr
