version: 2.1

executors:
  docker-publisher:
    docker:
      - image: cimg/base:2022.06

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: List all files 
          command: ls -al

      - run:
          name: Docker Hub login  
          command: echo ${PASSWORD} | docker login -u ${USERNAME} --password-stdin

      - run:
          name: Build and tag Docker image  
          command: |
           cd dolibarr
           docker build -t ${USERNAME}/dolibarr.dev:latest .
      - run:
          name: Push the image  
          command: docker push ${USERNAME}/dolibarr.dev:latest
workflows:
  dolibarr:
    jobs:
       - build:       
          filters:
             branches:
                only:
                   - master